version: "3"

services:
  raspi_kirim:
    build: 
      context: ./app
    restart: always
    volumes:
      - ./app:/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    privileged: true
